---
- name: Deploy Bitbucket App Node 2
  hosts: bitbucket-02
  become: true

  tasks:
    - name: check localhome dir is present
      file:
        path: "{{localhome}}"
        state: directory
        mode: '0755'
    - name: mount nfs
      mount:
        path: "{{sharedhome}}"
        src: "{{nfsserverip}}:{{nfspath}}"
        opts: "{{mountopts}}"
        state: mounted
        fstype: nfs
    - name: run bitbucket
      docker_container:
        name: bitbucket-02
        image: atlassian/bitbucket-server:{{version}} 
        state: started
        restart: yes
        restart_policy: "{{restartpolicy}}"
        ports:
         - "{{httpport}}:{{httpport}}"
         - "{{sshport}}:{{sshport}}"
         - "{{hazelcastport}}:{{hazelcastport}}"
        volumes: 
          - "{{localhome}}:/var/atlassian/application-data/bitbucket"
          - "{{sharedhome}}:/var/atlassian/application-data/bitbucket/shared"
        env:
          HAZELCAST_PORT: "{{hazelcastport}}"
          HAZELCAST_NODE_AUTHENTICATION_ENABLED: "{{hazelcastauthenabled}}"
          HAZELCAST_NETWORK_MULTICAST: "{{hazelcastmulticast}}"
          HAZELCAST_NETWORK_TCPIP: "{{hazelcasttcpip}}"
          HAZELCAST_NETWORK_TCPIP_MEMBERS: "{{bitbucketnode01ip}}:{{hazelcastport}}"
          HAZELCAST_LOCAL_PUBLIC_ADDRESS: "{{bitbucketnode02ip}}"
          ELASTICSEARCH_ENABLED: "{{elasticsearchenabled}}"
          JDBC_DRIVER: "{{jdbcdrivertype}}"
          JDBC_USER: "{{dbuser}}"
          JDBC_PASSWORD: "{{dbpassword}}"
          JDBC_URL: "jdbc:{{jdbctype}}://{{dbhost}}:{{dbport}}/{{database}}"

